<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('utf8');
E_D("DROP TABLE IF EXISTS `fanwe_deal`;");
E_C("CREATE TABLE `fanwe_deal` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `name_match` text NOT NULL,
  `name_match_row` text NOT NULL,
  `image` varchar(255) NOT NULL,
  `source_vedio` varchar(255) NOT NULL,
  `vedio` varchar(255) NOT NULL,
  `deal_days` int(11) NOT NULL COMMENT '上线天数，仅提供管理员审核参考',
  `begin_time` int(11) NOT NULL,
  `end_time` int(11) NOT NULL,
  `is_effect` tinyint(1) NOT NULL,
  `limit_price` decimal(20,2) NOT NULL COMMENT '项目金额',
  `brief` text NOT NULL,
  `description` text NOT NULL,
  `comment_count` int(11) NOT NULL,
  `support_count` int(11) NOT NULL COMMENT '支持人数',
  `focus_count` int(11) NOT NULL,
  `view_count` int(11) NOT NULL,
  `log_count` int(11) NOT NULL,
  `support_amount` decimal(20,2) NOT NULL COMMENT '支持总金额，需大等于limit_price(不含运费)',
  `pay_amount` decimal(20,2) NOT NULL COMMENT '可发放金额，抽完佣金的可领金额（含运费，运费不抽佣金）\r\n即support_amount*佣金比率+delivery_fee_amount',
  `delivery_fee_amount` decimal(20,2) NOT NULL COMMENT '交付费用金额',
  `create_time` int(11) NOT NULL,
  `seo_title` text NOT NULL,
  `seo_keyword` text NOT NULL,
  `seo_description` text NOT NULL,
  `tags` text NOT NULL,
  `tags_match` text NOT NULL,
  `tags_match_row` text NOT NULL,
  `success_time` int(11) NOT NULL,
  `is_success` tinyint(1) NOT NULL,
  `cate_id` int(11) NOT NULL,
  `province` varchar(255) NOT NULL,
  `city` varchar(255) NOT NULL,
  `user_id` int(11) NOT NULL,
  `sort` int(11) NOT NULL,
  `user_name` varchar(255) NOT NULL,
  `is_recommend` tinyint(1) NOT NULL COMMENT '推荐项目',
  `is_classic` tinyint(1) NOT NULL COMMENT '经典项目',
  `is_delete` tinyint(1) NOT NULL,
  `deal_extra_cache` text NOT NULL,
  `is_edit` tinyint(1) NOT NULL,
  `description_1` text NOT NULL,
  `is_support_print` int(11) NOT NULL,
  `user_level` int(11) NOT NULL,
  `is_has_send_success` tinyint(1) NOT NULL,
  `pay_radio` decimal(20,2) NOT NULL,
  `adv_image` varchar(255) NOT NULL COMMENT '广告图片',
  `status` tinyint(1) NOT NULL,
  `deal_background_image` varchar(255) NOT NULL COMMENT '项目背景图片',
  `deal_backgroundColor_image` varchar(255) NOT NULL COMMENT '项目底色图片',
  `type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0 表示普通众筹，1表示股权众筹,2表示众筹买房',
  `description_2` text NOT NULL COMMENT '目标用户或客户群体定位',
  `description_3` text NOT NULL COMMENT '目标用户或客户群体目前困扰或需求定位',
  `description_4` text NOT NULL COMMENT '满足目标用户或客户需求的产品或服务模式说明',
  `description_5` text NOT NULL COMMENT '项目赢利模式说明',
  `description_6` text NOT NULL COMMENT '市场主要同行或竞争对手概述',
  `description_7` text NOT NULL COMMENT '项目主要核心竞争力说明',
  `stock` text NOT NULL COMMENT '股东信息',
  `unstock` text NOT NULL COMMENT '非股东成员',
  `history` text NOT NULL COMMENT '三年信息',
  `plan` text NOT NULL COMMENT '三年计划',
  `attach` text NOT NULL COMMENT '附件信息',
  `investor_authority` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0表示只有投资人可以，1表所有人都可以看',
  `project_step` tinyint(1) NOT NULL COMMENT '项目阶段 0表示未启动 1表示在开发中 2产品已上市或上线，3已经有收入，4已经盈利',
  `business_create_time` int(11) NOT NULL COMMENT '企业成立时间',
  `business_employee_num` int(11) NOT NULL COMMENT '企业员工数量',
  `business_is_exist` tinyint(1) NOT NULL COMMENT '公司是否成立',
  `has_another_project` tinyint(1) NOT NULL COMMENT '是否有其他项目 0表示么有  1表示有',
  `business_name` varchar(255) NOT NULL COMMENT '公司名称',
  `business_address` varchar(255) NOT NULL COMMENT '办公地址',
  `business_stock_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '入股方式  0直接入股原公司 1 创建新公司入股',
  `business_pay_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '付款方式 0表示一次性付款',
  `business_descripe` text NOT NULL COMMENT '企业简介',
  `pay_end_time` int(11) NOT NULL COMMENT '支付结算时间',
  `investor_edit` int(1) NOT NULL COMMENT '0表示显示下一步按钮，1表示显示不错和返回按钮',
  `mine_stock` decimal(10,2) DEFAULT NULL COMMENT '投资人占有的股份',
  `transfer_share` decimal(10,2) NOT NULL,
  `virtual_num` int(11) NOT NULL COMMENT '虚拟人数',
  `virtual_price` decimal(20,2) NOT NULL COMMENT '虚拟金额',
  `gen_num` int(11) NOT NULL COMMENT '跟投人数',
  `xun_num` int(11) NOT NULL COMMENT '询价人数',
  `invote_money` decimal(20,2) NOT NULL COMMENT '预购金额',
  `invote_num` int(11) NOT NULL COMMENT '投资人数',
  `invote_mini_money` decimal(10,2) NOT NULL COMMENT '最低支付金额',
  `refuse_reason` text COMMENT '拒绝理由',
  `audit_data` text NOT NULL COMMENT '发起人资料',
  `is_hot` tinyint(1) NOT NULL DEFAULT '0' COMMENT '热门',
  `ips_bill_no` varchar(255) NOT NULL COMMENT '托管项目',
  `share_fee_amount` decimal(20,2) NOT NULL COMMENT '分红总金额',
  `is_special` tinyint(1) NOT NULL COMMENT '专题',
  `invest_status` tinyint(1) NOT NULL COMMENT '融资状态：0未确认，1成功，2失败',
  `left_money` decimal(20,2) NOT NULL COMMENT '剩余筹款',
  PRIMARY KEY (`id`),
  KEY `begin_time` (`begin_time`),
  KEY `end_time` (`end_time`),
  KEY `is_effect` (`is_effect`),
  KEY `limit_price` (`limit_price`),
  KEY `comment_count` (`comment_count`),
  KEY `support_count` (`support_count`),
  KEY `focus_count` (`focus_count`),
  KEY `view_count` (`view_count`),
  KEY `log_count` (`log_count`),
  KEY `support_amount` (`support_amount`),
  KEY `create_time` (`create_time`),
  KEY `is_success` (`is_success`),
  KEY `cate_id` (`cate_id`),
  KEY `sort` (`sort`),
  KEY `is_recommend` (`is_recommend`),
  KEY `is_classic` (`is_classic`),
  KEY `is_delete` (`is_delete`),
  FULLTEXT KEY `tags_match` (`tags_match`),
  FULLTEXT KEY `name_match` (`name_match`)
) ENGINE=MyISAM AUTO_INCREMENT=157 DEFAULT CHARSET=utf8");
E_D("replace into `fanwe_deal` values('155','项目名称：泡温泉','ux28201ux27849,ux21517ux31216,ux39033ux30446,ux39033ux30446ux21517ux31216ux65306ux27873ux28201ux27849','温泉,名称,项目,项目名称：泡温泉','./public/attachment/201508/17/13/55d1701794f62.jpg','http://player.youku.com/embed/XMjgxNjMzNjI4','http://v.youku.com/v_show/id_XMjgxNjMzNjI4.html','20','1439760386','1450387588','1','11000.00','简要说明','<h3>\r\n	关于我\r\n</h3>\r\n<p>\r\n	向支持者介绍一下你自己，以及你与所发起的项目之间的背景。这样有助于拉近你与支持者之间的距离。建议不超过100字。\r\n</p>\r\n<h3>\r\n	我想要做什么\r\n</h3>\r\n<p>\r\n	以图文并茂的方式简洁生动地说明你的项目，让大家一目了然，这会决定是否将你的项目描述继续看下去。建议不超过300字。\r\n</p>\r\n<h3>\r\n	为什么我需要你的支持\r\n</h3>\r\n<p>\r\n	这是加分项。说说你的项目不同寻常的特色、资金用途、以及大家支持你的理由。这会让更多人能够支持你，不超过200个汉字。\r\n</p>\r\n<h3>\r\n	我的承诺与回报\r\n</h3>\r\n让大家感到你对待项目的认真程度，鞭策你将项目执行最终成功。同时向大家展示一下你为支持者准备的回报，来吸引更多人支持你。','0','1','0','5','0','200.00','200.00','0.00','1439760313','','','','温泉 名称 项目','ux28201ux27849,ux21517ux31216,ux39033ux30446','温泉,名称,项目','0','0','9','安徽','宿州','20','0','myname','1','1','0','a:2:{s:13:\"deal_faq_list\";a:0:{}s:14:\"deal_item_list\";a:2:{i:0;a:17:{s:2:\"id\";s:3:\"247\";s:7:\"deal_id\";s:3:\"155\";s:5:\"price\";s:6:\"100.00\";s:13:\"support_count\";s:1:\"0\";s:14:\"support_amount\";s:4:\"0.00\";s:11:\"description\";s:63:\"获得回报优惠券获得回报优惠券获得回报优惠券\";s:11:\"is_delivery\";s:1:\"0\";s:12:\"delivery_fee\";s:4:\"0.00\";s:13:\"is_limit_user\";s:1:\"0\";s:10:\"limit_user\";s:1:\"0\";s:10:\"repaid_day\";s:2:\"10\";s:14:\"virtual_person\";s:1:\"0\";s:8:\"is_share\";s:1:\"0\";s:9:\"share_fee\";s:4:\"0.00\";s:4:\"type\";s:1:\"0\";s:6:\"images\";a:1:{i:0;a:4:{s:2:\"id\";s:3:\"187\";s:7:\"deal_id\";s:3:\"155\";s:12:\"deal_item_id\";s:3:\"247\";s:5:\"image\";s:50:\"./public/attachment/201508/17/13/55d17052970d3.jpg\";}}s:12:\"price_format\";s:3:\"100\";}i:1;a:17:{s:2:\"id\";s:3:\"248\";s:7:\"deal_id\";s:3:\"155\";s:5:\"price\";s:6:\"200.00\";s:13:\"support_count\";s:1:\"1\";s:14:\"support_amount\";s:6:\"200.00\";s:11:\"description\";s:147:\"获得回报优惠券获得回报优惠券获得回报优惠券获得回报优惠券获得回报优惠券获得回报优惠券获得回报优惠券\";s:11:\"is_delivery\";s:1:\"0\";s:12:\"delivery_fee\";s:4:\"0.00\";s:13:\"is_limit_user\";s:1:\"0\";s:10:\"limit_user\";s:1:\"0\";s:10:\"repaid_day\";s:1:\"0\";s:14:\"virtual_person\";s:1:\"0\";s:8:\"is_share\";s:1:\"0\";s:9:\"share_fee\";s:4:\"0.00\";s:4:\"type\";s:1:\"0\";s:6:\"images\";a:1:{i:0;a:4:{s:2:\"id\";s:3:\"188\";s:7:\"deal_id\";s:3:\"155\";s:12:\"deal_item_id\";s:3:\"248\";s:5:\"image\";s:50:\"./public/attachment/201508/17/13/55d17065f2414.png\";}}s:12:\"price_format\";s:3:\"200\";}}}','0','','1','0','0','0.00','','0','','','0','','','','','','','','','','','','0','0','0','0','0','0','','','0','0','','0','0','0.00','0.00','0','0.00','0','0','0.00','0','0.00','','','1','','0.00','1','0','0.00');");
E_D("replace into `fanwe_deal` values('156','度假酒店','ux24230ux20551,ux37202ux24215,ux24230ux20551ux37202ux24215','度假,酒店,度假酒店','./public/attachment/201508/17/13/55d17188b7a6f.jpg','http://player.youku.com/embed/XMjgxNjMzNjI4','http://v.youku.com/v_show/id_XMjgxNjMzNjI4.html','0','1439760866','1460756070','1','10000000.00','','','0','0','0','1','0','0.00','0.00','0.00','1439760691','','','','酒店','ux37202ux24215','酒店','0','1','2','广东','广州','20','0','myname','1','1','0','','0','','0','0','1','0.00','','0','','','1','<span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">目标用户或客户群体定位</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">目标用户或客户群体定位</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">目标用户或客户群体定位</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">目标用户或客户群体定位</span>','<span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">目标用户或客户群体目前困扰或需求定位</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">目标用户或客户群体目前困扰或需求定位</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">目标用户或客户群体目前困扰或需求定位</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">目标用户或客户群体目前困扰或需求定位</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">目标用户或客户群体目前困扰或需求定位</span>','<span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">满足目标用户或客户需求的产品或服务模式说明</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">满足目标用户或客户需求的产品或服务模式说明</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">满足目标用户或客户需求的产品或服务模式说明</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">满足目标用户或客户需求的产品或服务模式说明</span>','<span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">项目赢利模式说明</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">项目赢利模式说明</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">项目赢利模式说明</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">项目赢利模式说明</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">项目赢利模式说明</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">项目赢利模式说明</span>','<span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">市场主要同行或竞争对手概述</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">市场主要同行或竞争对手概述</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">市场主要同行或竞争对手概述</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">市场主要同行或竞争对手概述</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">市场主要同行或竞争对手概述</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">市场主要同行或竞争对手概述</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">市场主要同行或竞争对手概述</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">市场主要同行或竞争对手概述</span>','<span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">项目主要核心竞争力说明</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">项目主要核心竞争力说明</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">项目主要核心竞争力说明</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">项目主要核心竞争力说明</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">项目主要核心竞争力说明</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">项目主要核心竞争力说明</span>','a:1:{i:0;a:7:{s:4:\"name\";s:9:\"读懂人\";s:3:\"job\";s:6:\"职位\";s:12:\"is_full_time\";s:6:\"全职\";s:5:\"share\";d:100;s:12:\"invest_money\";s:3:\"200\";s:8:\"relation\";s:0:\"\";s:8:\"describe\";s:615:\"<span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">项目主要核心竞争力说明</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">项目主要核心竞争力说明</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">项目主要核心竞争力说明</span>\";}}','a:0:{}','a:1:{i:0;a:1:{s:4:\"info\";a:11:{s:4:\"name\";s:10:\"第1阶段\";s:10:\"begin_time\";s:8:\"2015-8-4\";s:8:\"end_time\";s:9:\"2015-8-31\";s:8:\"describe\";s:1080:\"<span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">第</span><span class=\"daxie\" style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">1</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">阶段</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">第</span><span class=\"daxie\" style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">1</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">阶段</span>\";s:11:\"do_describe\";s:1620:\"<span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">第</span><span class=\"daxie\" style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">1</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">阶段</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">第</span><span class=\"daxie\" style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">1</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">阶段</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">第</span><span class=\"daxie\" style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">1</span><span style=\"color:#3D9EEB;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:18px;line-height:40px;background-color:#FFFFFF;\">阶段</span>\";s:9:\"is_income\";s:1:\"0\";s:11:\"item_income\";s:1:\"0\";s:6:\"is_out\";s:1:\"0\";s:8:\"item_out\";s:1:\"0\";s:10:\"income_num\";i:1;s:7:\"out_num\";i:1;}}}','a:0:{}','a:1:{i:0;a:2:{s:5:\"title\";s:6:\"附件\";s:4:\"file\";s:71:\"http://ext4.ihancc.com/public/attachment/201508/17/13/55d172389c50d.txt\";}}','0','3','1438588800','200','1','1','度假酒店','度假酒店度假酒店','0','0','度假酒店度假酒店度假酒店度假酒店度假酒店度假酒店度假酒店度假酒店度假酒店','1471037675','1','0.00','10.00','0','0.00','1','0','10000000.00','1','1000000.00','','a:7:{s:8:\"legal_id\";a:4:{s:5:\"image\";a:1:{i:0;s:50:\"./public/attachment/201508/17/13/55d1719d2ebc4.jpg\";}s:6:\"status\";s:1:\"1\";s:6:\"reason\";s:0:\"\";s:12:\"display_type\";s:1:\"0\";}s:12:\"legal_credit\";a:4:{s:5:\"image\";a:1:{i:0;s:50:\"./public/attachment/201508/17/13/55d1719f458b9.jpg\";}s:6:\"status\";s:1:\"1\";s:6:\"reason\";s:0:\"\";s:12:\"display_type\";s:1:\"0\";}s:16:\"business_license\";a:4:{s:5:\"image\";a:1:{i:0;s:50:\"./public/attachment/201508/17/13/55d171a186616.jpg\";}s:6:\"status\";s:1:\"1\";s:6:\"reason\";s:0:\"\";s:12:\"display_type\";s:1:\"0\";}s:28:\"tax_registration_certificate\";a:4:{s:5:\"image\";a:1:{i:0;s:50:\"./public/attachment/201508/17/13/55d171a3bf205.jpg\";}s:6:\"status\";s:1:\"1\";s:6:\"reason\";s:0:\"\";s:12:\"display_type\";s:1:\"0\";}s:17:\"organization_code\";a:4:{s:5:\"image\";a:1:{i:0;s:50:\"./public/attachment/201508/17/13/55d171a5bb8ef.jpg\";}s:6:\"status\";s:1:\"1\";s:6:\"reason\";s:0:\"\";s:12:\"display_type\";s:1:\"0\";}s:13:\"company_photo\";a:4:{s:5:\"image\";a:1:{i:0;s:50:\"./public/attachment/201508/17/13/55d171a772efe.jpg\";}s:6:\"status\";s:1:\"1\";s:6:\"reason\";s:0:\"\";s:12:\"display_type\";s:1:\"0\";}s:13:\"site_contract\";a:4:{s:5:\"image\";a:1:{i:0;s:50:\"./public/attachment/201508/17/13/55d171a973470.jpg\";}s:6:\"status\";s:1:\"1\";s:6:\"reason\";s:0:\"\";s:12:\"display_type\";s:1:\"0\";}}','1','','0.00','1','0','0.00');");

require("../../inc/footer.php");
?>