<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('utf8');
E_D("DROP TABLE IF EXISTS `fanwe_sql_check`;");
E_C("CREATE TABLE `fanwe_sql_check` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `module` varchar(255) NOT NULL,
  `action` varchar(255) NOT NULL,
  `module_action` varchar(255) NOT NULL,
  `para` varchar(255) NOT NULL COMMENT '参数',
  `module_action_para` varchar(255) NOT NULL,
  `sql_num` int(11) NOT NULL,
  `sql_str` text NOT NULL,
  `query_time` float(11,6) NOT NULL DEFAULT '0.000000' COMMENT 'SQL运行时间',
  `run_time` float(11,6) NOT NULL DEFAULT '0.000000' COMMENT '运行时间',
  `memory_usage` float(11,4) NOT NULL DEFAULT '0.0000' COMMENT '内存占用情况',
  `gzip_on` tinyint(1) NOT NULL COMMENT '是否开启gzip_on',
  `url` varchar(255) NOT NULL COMMENT '请求地址',
  `file_name` varchar(255) NOT NULL,
  `create_time` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=279264 DEFAULT CHARSET=utf8");
E_D("replace into `fanwe_sql_check` values('279256','deals','index','deals-index','type-id','deals-index-type-id','11','a:12:{i:0;s:109:\"delete from fanwe_deal_order where order_status = 0 and credit_pay = 0 and  1439763943 - create_time > 259200\";i:1;s:38:\"select count(*) from fanwe_deal_notify\";i:2;s:52:\"select * from  fanwe_link_group where is_effect = 1 \";i:3;s:100:\"select * from fanwe_link where is_effect = 1 and show_index = 1 and group_id = 14 order by sort desc\";i:4;s:51:\"select * from  fanwe_collocation where is_effect=1 \";i:5;s:98:\"select province from fanwe_deal where type=1 and is_effect =1 group by province  order by sort asc\";i:6;s:152:\"select rc.* from fanwe_region_conf as rc where rc.name in (select province from fanwe_deal) or  rc.name in (select city from fanwe_deal) or rc.is_hot=1 \";i:7;s:167:\"select count(*)  from fanwe_deal as d  where  1=1 AND d.is_delete = 0 AND d.is_effect = 1  AND  d.is_delete = 0 and d.is_effect = 1  and d.cate_id in (8) and d.type=1 \";i:8;s:31:\"select * from fanwe_deal_level \";i:9;s:85:\"select * from fanwe_adv where tmpl=''fanwe_1'' and adv_id=''deals_top'' and is_effect = 1\";i:10;s:88:\"select * from fanwe_adv where tmpl=''fanwe_1'' and adv_id=''deals_bottom'' and is_effect = 1\";i:11;s:100:\"select sql_num from fanwe_sql_check where module_action_para=''deals-index-type-id'' order by id desc \";}','0.010474','0.104115','5.3500','1','http://ext4.ihancc.com/deals/id-8-type-1.html','index.php','1439763943');");
E_D("replace into `fanwe_sql_check` values('279257','settings','index','settings-index','','settings-index','7','a:8:{i:0;s:56:\"select * from fanwe_user where id = 20 and is_effect = 1\";i:1;s:45:\"select level from fanwe_user_level where id=0\";i:2;s:109:\"delete from fanwe_deal_order where order_status = 0 and credit_pay = 0 and  1439764327 - create_time > 259200\";i:3;s:38:\"select count(*) from fanwe_deal_notify\";i:4;s:35:\"select code,val from fanwe_m_config\";i:5;s:47:\"select * from fanwe_deal_cate order by sort asc\";i:6;s:51:\"select * from  fanwe_collocation where is_effect=1 \";i:7;s:95:\"select sql_num from fanwe_sql_check where module_action_para=''settings-index'' order by id desc \";}','0.002194','0.064038','4.4900','1','http://ext4.ihancc.com/wap/index.php?ctl=settings','index.php','1439764327');");
E_D("replace into `fanwe_sql_check` values('279258','settings','modify','settings-modify','','settings-modify','10','a:11:{i:0;s:56:\"select * from fanwe_user where id = 20 and is_effect = 1\";i:1;s:45:\"select level from fanwe_user_level where id=0\";i:2;s:109:\"delete from fanwe_deal_order where order_status = 0 and credit_pay = 0 and  1439764331 - create_time > 259200\";i:3;s:38:\"select count(*) from fanwe_deal_notify\";i:4;s:35:\"select code,val from fanwe_m_config\";i:5;s:47:\"select * from fanwe_deal_cate order by sort asc\";i:6;s:51:\"select * from  fanwe_collocation where is_effect=1 \";i:7;s:70:\"select * from fanwe_region_conf where region_level = 2 order by py asc\";i:8;s:62:\"select * from fanwe_region_conf where pid = 11 order by py asc\";i:9;s:49:\"select * from fanwe_user_weibo where user_id = 20\";i:10;s:96:\"select sql_num from fanwe_sql_check where module_action_para=''settings-modify'' order by id desc \";}','0.002683','0.104287','4.6800','1','http://ext4.ihancc.com/wap/index.php?ctl=settings&act=modify','index.php','1439764331');");
E_D("replace into `fanwe_sql_check` values('279259','settings','consignee','settings-consignee','','settings-consignee','8','a:9:{i:0;s:56:\"select * from fanwe_user where id = 20 and is_effect = 1\";i:1;s:45:\"select level from fanwe_user_level where id=0\";i:2;s:109:\"delete from fanwe_deal_order where order_status = 0 and credit_pay = 0 and  1439764334 - create_time > 259200\";i:3;s:38:\"select count(*) from fanwe_deal_notify\";i:4;s:35:\"select code,val from fanwe_m_config\";i:5;s:47:\"select * from fanwe_deal_cate order by sort asc\";i:6;s:51:\"select * from  fanwe_collocation where is_effect=1 \";i:7;s:53:\"select * from fanwe_user_consignee where user_id = 20\";i:8;s:99:\"select sql_num from fanwe_sql_check where module_action_para=''settings-consignee'' order by id desc \";}','0.002417','0.047022','4.4600','1','http://ext4.ihancc.com/wap/index.php?ctl=settings&act=consignee','index.php','1439764334');");
E_D("replace into `fanwe_sql_check` values('279260','settings','add_consignee','settings-add_consignee','','settings-add_consignee','8','a:9:{i:0;s:56:\"select * from fanwe_user where id = 20 and is_effect = 1\";i:1;s:45:\"select level from fanwe_user_level where id=0\";i:2;s:109:\"delete from fanwe_deal_order where order_status = 0 and credit_pay = 0 and  1439764336 - create_time > 259200\";i:3;s:38:\"select count(*) from fanwe_deal_notify\";i:4;s:35:\"select code,val from fanwe_m_config\";i:5;s:47:\"select * from fanwe_deal_cate order by sort asc\";i:6;s:51:\"select * from  fanwe_collocation where is_effect=1 \";i:7;s:70:\"select * from fanwe_region_conf where region_level = 2 order by py asc\";i:8;s:103:\"select sql_num from fanwe_sql_check where module_action_para=''settings-add_consignee'' order by id desc \";}','0.002070','0.048058','4.5000','1','http://ext4.ihancc.com/wap/index.php?ctl=settings&act=add_consignee','index.php','1439764336');");
E_D("replace into `fanwe_sql_check` values('279261','settings','add_consignee','settings-add_consignee','id','settings-add_consignee-id','10','a:11:{i:0;s:56:\"select * from fanwe_user where id = 20 and is_effect = 1\";i:1;s:45:\"select level from fanwe_user_level where id=0\";i:2;s:109:\"delete from fanwe_deal_order where order_status = 0 and credit_pay = 0 and  1439764358 - create_time > 259200\";i:3;s:38:\"select count(*) from fanwe_deal_notify\";i:4;s:35:\"select code,val from fanwe_m_config\";i:5;s:47:\"select * from fanwe_deal_cate order by sort asc\";i:6;s:51:\"select * from  fanwe_collocation where is_effect=1 \";i:7;s:65:\"select * from fanwe_user_consignee where id = 38 and user_id = 20\";i:8;s:70:\"select * from fanwe_region_conf where region_level = 2 order by py asc\";i:9;s:63:\"select * from fanwe_region_conf where pid = 396 order by py asc\";i:10;s:106:\"select sql_num from fanwe_sql_check where module_action_para=''settings-add_consignee-id'' order by id desc \";}','0.002717','0.048017','4.5000','1','http://ext4.ihancc.com/wap/index.php?ctl=settings&act=add_consignee&id=38','index.php','1439764358');");
E_D("replace into `fanwe_sql_check` values('279262','account','point','account-point','','account-point','9','a:10:{i:0;s:56:\"select * from fanwe_user where id = 20 and is_effect = 1\";i:1;s:45:\"select level from fanwe_user_level where id=0\";i:2;s:109:\"delete from fanwe_deal_order where order_status = 0 and credit_pay = 0 and  1439764438 - create_time > 259200\";i:3;s:38:\"select count(*) from fanwe_deal_notify\";i:4;s:35:\"select code,val from fanwe_m_config\";i:5;s:47:\"select * from fanwe_deal_cate order by sort asc\";i:6;s:51:\"select * from  fanwe_collocation where is_effect=1 \";i:7;s:104:\"select * from fanwe_user_log where user_id = 20 and point <>0  order by log_time desc,id desc limit 0,10\";i:8;s:68:\"select count(*) from fanwe_user_log where user_id = 20 and point <>0\";i:9;s:94:\"select sql_num from fanwe_sql_check where module_action_para=''account-point'' order by id desc \";}','0.002093','0.054553','4.9100','1','http://ext4.ihancc.com/wap/index.php?ctl=account&act=point','index.php','1439764438');");
E_D("replace into `fanwe_sql_check` values('279263','user','login','user-login','','user-login','5','a:6:{i:0;s:109:\"delete from fanwe_deal_order where order_status = 0 and credit_pay = 0 and  1439764438 - create_time > 259200\";i:1;s:38:\"select count(*) from fanwe_deal_notify\";i:2;s:35:\"select code,val from fanwe_m_config\";i:3;s:47:\"select * from fanwe_deal_cate order by sort asc\";i:4;s:51:\"select * from  fanwe_collocation where is_effect=1 \";i:5;s:91:\"select sql_num from fanwe_sql_check where module_action_para=''user-login'' order by id desc \";}','0.001040','0.045119','4.3600','1','http://ext4.ihancc.com/wap/index.php?ctl=user&act=login','index.php','1439764438');");

require("../../inc/footer.php");
?>