<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('utf8');
E_D("DROP TABLE IF EXISTS `fanwe_article`;");
E_C("CREATE TABLE `fanwe_article` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL COMMENT '文章标题',
  `content` text NOT NULL COMMENT ' 文章内容',
  `cate_id` int(11) NOT NULL COMMENT '文章分类ID',
  `create_time` int(11) NOT NULL COMMENT '发表时间',
  `update_time` int(11) NOT NULL COMMENT '更新时间',
  `add_admin_id` int(11) NOT NULL COMMENT '发布人(管理员ID)',
  `is_effect` tinyint(4) NOT NULL COMMENT '有效性标识',
  `rel_url` varchar(255) NOT NULL COMMENT '自动跳转的外链',
  `update_admin_id` int(11) NOT NULL COMMENT '更新人(管理员ID)',
  `is_delete` tinyint(4) NOT NULL COMMENT '删除标识',
  `click_count` int(11) NOT NULL COMMENT '点击数',
  `sort` int(11) NOT NULL COMMENT '排序 由大到小',
  `seo_title` text NOT NULL COMMENT '自定义seo页面标题',
  `seo_keyword` text NOT NULL COMMENT '自定义seo页面keyword',
  `seo_description` text NOT NULL COMMENT '自定义seo页面标述',
  `uname` varchar(255) NOT NULL,
  `sub_title` varchar(255) NOT NULL,
  `brief` text NOT NULL,
  `is_week` tinyint(1) NOT NULL,
  `is_hot` tinyint(1) NOT NULL,
  `icon` varchar(255) NOT NULL COMMENT '展示图表',
  `writer` varchar(255) NOT NULL COMMENT '发布者',
  `tags` varchar(255) NOT NULL COMMENT '标签',
  PRIMARY KEY (`id`),
  KEY `cate_id` (`cate_id`),
  KEY `create_time` (`create_time`),
  KEY `update_time` (`update_time`),
  KEY `click_count` (`click_count`),
  KEY `sort` (`sort`)
) ENGINE=MyISAM AUTO_INCREMENT=5305 DEFAULT CHARSET=utf8");
E_D("replace into `fanwe_article` values('68','关于我们','关于方维众筹 \r\n众筹，译自国外crowdfunding一词，即大众筹资或群众筹资。是指用团购+预购的形式，向网友募集项目资金的模式。众筹利用互联网和SNS传播的特性，让许多有梦想的人可以向公众展示自己的创意，发起项目争取别人的支持与帮助，进而获得所需要的援助，支持者则会获得实物、服务等不同形式的回报。\r\n众筹是一个协助亲们发起创意、梦想的平台，不论你是学生、白领、艺术家、明星，如果你有一个想完成的计划（例如：电影、音乐、动漫、设计、公益等），你可以在此发起项目向大家展示你的计划，并邀请喜欢你的计划的人以资金支持你。如果你愿意帮助别人，支持别人的梦想，你可以在众筹浏览到各行各业的人发起的项目计划，也可以成为发起人的梦想合伙人，当你们一起见证项目成功后，你还会获得发起人感谢你支持的回报。','22','1413251192','1439758696','0','1','','0','0','0','1','','','','','','','1','1','','众筹网','众筹网');");
E_D("replace into `fanwe_article` values('72','常见问题','<div style=\"text-align:center;\">\r\n	<!--[if gte mso 9]>MicrosoftInternetExplorer402DocumentNotSpecified7.8Normal0<![endif]-->\r\n	<p class=\"p0\" align=\"center\">\r\n		<b><span style=\"font-size:18px;font-family:\" 宋体\";\"=\"\"><span style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;line-height:21px;background-color:#E56600;\">关于方维众筹&nbsp;</span><br />\r\n<br />\r\n		<p style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;background-color:#FFFFFF;\">\r\n			众筹，译自国外crowdfunding一词，即大众筹资或群众筹资。是指用团购+预购的形式，向网友募集项目资金的模式。众筹利用互联网和SNS传播的特性，让许多有梦想的人可以向公众展示自己的创意，发起项目争取别人的支持与帮助，进而获得所需要的援助，支持者则会获得实物、服务等不同形式的回报。\r\n		</p>\r\n		<p style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;background-color:#FFFFFF;\">\r\n			<br />\r\n		</p>\r\n<span style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;line-height:21px;background-color:#FFFFFF;\">众筹是一个协助亲们发起创意、梦想的平台，不论你是学生、白领、艺术家、明星，如果你有一个想完成的计划（例如：电影、音乐、动漫、设计、公益等），你可以在此发起项目向大家展示你的计划，并邀请喜欢你的计划的人以资金支持你。如果你愿意帮助别人，支持别人的梦想，你可以在众筹浏览到各行各业的人发起的项目计划，也可以成为发起人的梦想合伙人，当你们一起见证项目成功后，你还会获得发起人感谢你支持的回报。</span><br />\r\n</span></b>\r\n	</p>\r\n	<p class=\"p0\" style=\"margin-left:18.0000pt;\" align=\"left\">\r\n		<span style=\"font-size:14px;\" 宋体\";\"=\"\"><span><span style=\"font-size:14px;\"></span></span></span>\r\n	</p>\r\n<!--[if gte mso 9]><![endif]-->\r\n</div>','24','1413338371','1415497866','0','1','http://www.qmct8.com/index.php?ctl=faq','0','0','0','5','','','','','','','1','1','','众筹网','众筹网');");
E_D("replace into `fanwe_article` values('77','项目规范','<div style=\"text-align:center;\">\r\n	<!--[if gte mso 9]>MicrosoftInternetExplorer402DocumentNotSpecified7.8Normal0<![endif]-->\r\n	<p class=\"p0\" align=\"center\">\r\n		<b><span style=\"font-size:18px;font-family:\" 宋体\";\"=\"\"><span style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;line-height:21px;background-color:#E56600;\">关于方维众筹&nbsp;</span><br />\r\n<br />\r\n		<p style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;background-color:#FFFFFF;\">\r\n			众筹，译自国外crowdfunding一词，即大众筹资或群众筹资。是指用团购+预购的形式，向网友募集项目资金的模式。众筹利用互联网和SNS传播的特性，让许多有梦想的人可以向公众展示自己的创意，发起项目争取别人的支持与帮助，进而获得所需要的援助，支持者则会获得实物、服务等不同形式的回报。\r\n		</p>\r\n		<p style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;background-color:#FFFFFF;\">\r\n			<br />\r\n		</p>\r\n<span style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;line-height:21px;background-color:#FFFFFF;\">众筹是一个协助亲们发起创意、梦想的平台，不论你是学生、白领、艺术家、明星，如果你有一个想完成的计划（例如：电影、音乐、动漫、设计、公益等），你可以在此发起项目向大家展示你的计划，并邀请喜欢你的计划的人以资金支持你。如果你愿意帮助别人，支持别人的梦想，你可以在众筹浏览到各行各业的人发起的项目计划，也可以成为发起人的梦想合伙人，当你们一起见证项目成功后，你还会获得发起人感谢你支持的回报。</span><br />\r\n</span></b>\r\n	</p>\r\n	<p class=\"p0\" style=\"margin-left:18.0000pt;\" align=\"left\">\r\n		<span style=\"font-size:14px;\" 宋体\";\"=\"\"><span><span style=\"font-size:14px;\"></span></span></span>\r\n	</p>\r\n<!--[if gte mso 9]><![endif]-->\r\n</div>','28','1413588165','1420329120','0','1','','0','0','0','9','','','','','','','1','1','','众筹网','众筹网');");
E_D("replace into `fanwe_article` values('75','使用条款','<div style=\"text-align:center;\">\r\n	<!--[if gte mso 9]>MicrosoftInternetExplorer402DocumentNotSpecified7.8Normal0<![endif]-->\r\n	<p class=\"p0\" align=\"center\">\r\n		<b><span style=\"font-size:18px;font-family:\" 宋体\";\"=\"\"><span style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;line-height:21px;background-color:#E56600;\">关于方维众筹&nbsp;</span><br />\r\n<br />\r\n		<p style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;background-color:#FFFFFF;\">\r\n			众筹，译自国外crowdfunding一词，即大众筹资或群众筹资。是指用团购+预购的形式，向网友募集项目资金的模式。众筹利用互联网和SNS传播的特性，让许多有梦想的人可以向公众展示自己的创意，发起项目争取别人的支持与帮助，进而获得所需要的援助，支持者则会获得实物、服务等不同形式的回报。\r\n		</p>\r\n		<p style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;background-color:#FFFFFF;\">\r\n			<br />\r\n		</p>\r\n<span style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;line-height:21px;background-color:#FFFFFF;\">众筹是一个协助亲们发起创意、梦想的平台，不论你是学生、白领、艺术家、明星，如果你有一个想完成的计划（例如：电影、音乐、动漫、设计、公益等），你可以在此发起项目向大家展示你的计划，并邀请喜欢你的计划的人以资金支持你。如果你愿意帮助别人，支持别人的梦想，你可以在众筹浏览到各行各业的人发起的项目计划，也可以成为发起人的梦想合伙人，当你们一起见证项目成功后，你还会获得发起人感谢你支持的回报。</span><br />\r\n</span></b>\r\n	</p>\r\n	<p class=\"p0\" style=\"margin-left:18.0000pt;\" align=\"left\">\r\n		<span style=\"font-size:14px;\" 宋体\";\"=\"\"><span><span style=\"font-size:14px;\"></span></span></span>\r\n	</p>\r\n<!--[if gte mso 9]><![endif]-->\r\n</div>','21','1413586458','1415669979','0','1','','0','0','0','7','','','','','','','1','1','','众筹网','众筹网');");
E_D("replace into `fanwe_article` values('78','版权申明','<div style=\"text-align:center;\">\r\n	<!--[if gte mso 9]>MicrosoftInternetExplorer402DocumentNotSpecified7.8Normal0<![endif]-->\r\n	<p class=\"p0\" align=\"center\">\r\n		<b><span style=\"font-size:18px;font-family:\" 宋体\";\"=\"\"><span style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;line-height:21px;background-color:#E56600;\">关于方维众筹&nbsp;</span><br />\r\n<br />\r\n		<p style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;background-color:#FFFFFF;\">\r\n			众筹，译自国外crowdfunding一词，即大众筹资或群众筹资。是指用团购+预购的形式，向网友募集项目资金的模式。众筹利用互联网和SNS传播的特性，让许多有梦想的人可以向公众展示自己的创意，发起项目争取别人的支持与帮助，进而获得所需要的援助，支持者则会获得实物、服务等不同形式的回报。\r\n		</p>\r\n		<p style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;background-color:#FFFFFF;\">\r\n			<br />\r\n		</p>\r\n<span style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;line-height:21px;background-color:#FFFFFF;\">众筹是一个协助亲们发起创意、梦想的平台，不论你是学生、白领、艺术家、明星，如果你有一个想完成的计划（例如：电影、音乐、动漫、设计、公益等），你可以在此发起项目向大家展示你的计划，并邀请喜欢你的计划的人以资金支持你。如果你愿意帮助别人，支持别人的梦想，你可以在众筹浏览到各行各业的人发起的项目计划，也可以成为发起人的梦想合伙人，当你们一起见证项目成功后，你还会获得发起人感谢你支持的回报。</span><br />\r\n</span></b>\r\n	</p>\r\n	<p class=\"p0\" style=\"margin-left:18.0000pt;\" align=\"left\">\r\n		<span style=\"font-size:14px;\" 宋体\";\"=\"\"><span><span style=\"font-size:14px;\"></span></span></span>\r\n	</p>\r\n<!--[if gte mso 9]><![endif]-->\r\n</div>','21','1413588553','1413588553','0','1','','0','0','0','10','','','','','','','1','1','','众筹网','众筹网');");
E_D("replace into `fanwe_article` values('79','风险提示','<div style=\"text-align:center;\">\r\n	<!--[if gte mso 9]>MicrosoftInternetExplorer402DocumentNotSpecified7.8Normal0<![endif]-->\r\n	<p class=\"p0\" align=\"center\">\r\n		<b><span style=\"font-size:18px;font-family:\" 宋体\";\"=\"\"><span style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;line-height:21px;background-color:#E56600;\">关于方维众筹&nbsp;</span><br />\r\n<br />\r\n		<p style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;background-color:#FFFFFF;\">\r\n			众筹，译自国外crowdfunding一词，即大众筹资或群众筹资。是指用团购+预购的形式，向网友募集项目资金的模式。众筹利用互联网和SNS传播的特性，让许多有梦想的人可以向公众展示自己的创意，发起项目争取别人的支持与帮助，进而获得所需要的援助，支持者则会获得实物、服务等不同形式的回报。\r\n		</p>\r\n		<p style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;background-color:#FFFFFF;\">\r\n			<br />\r\n		</p>\r\n<span style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;line-height:21px;background-color:#FFFFFF;\">众筹是一个协助亲们发起创意、梦想的平台，不论你是学生、白领、艺术家、明星，如果你有一个想完成的计划（例如：电影、音乐、动漫、设计、公益等），你可以在此发起项目向大家展示你的计划，并邀请喜欢你的计划的人以资金支持你。如果你愿意帮助别人，支持别人的梦想，你可以在众筹浏览到各行各业的人发起的项目计划，也可以成为发起人的梦想合伙人，当你们一起见证项目成功后，你还会获得发起人感谢你支持的回报。</span><br />\r\n</span></b>\r\n	</p>\r\n	<p class=\"p0\" style=\"margin-left:18.0000pt;\" align=\"left\">\r\n		<span style=\"font-size:14px;\" 宋体\";\"=\"\"><span><span style=\"font-size:14px;\"></span></span></span>\r\n	</p>\r\n<!--[if gte mso 9]><![endif]-->\r\n</div>','28','1413588976','1419460327','0','1','','0','0','0','11','','','','/fxts','','','1','1','','众筹网','众筹网');");
E_D("replace into `fanwe_article` values('85','业务流程','<div style=\"text-align:center;\">\r\n	<!--[if gte mso 9]>MicrosoftInternetExplorer402DocumentNotSpecified7.8Normal0<![endif]-->\r\n	<p class=\"p0\" align=\"center\">\r\n		<b><span style=\"font-size:18px;font-family:\" 宋体\";\"=\"\"><span style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;line-height:21px;background-color:#E56600;\">关于方维众筹&nbsp;</span><br />\r\n<br />\r\n		<p style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;background-color:#FFFFFF;\">\r\n			众筹，译自国外crowdfunding一词，即大众筹资或群众筹资。是指用团购+预购的形式，向网友募集项目资金的模式。众筹利用互联网和SNS传播的特性，让许多有梦想的人可以向公众展示自己的创意，发起项目争取别人的支持与帮助，进而获得所需要的援助，支持者则会获得实物、服务等不同形式的回报。\r\n		</p>\r\n		<p style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;background-color:#FFFFFF;\">\r\n			<br />\r\n		</p>\r\n<span style=\"color:#404040;font-family:''Microsoft Yahei'', 微软雅黑, Arial, ''Hiragino Sans GB'', 宋体;font-size:14px;line-height:21px;background-color:#FFFFFF;\">众筹是一个协助亲们发起创意、梦想的平台，不论你是学生、白领、艺术家、明星，如果你有一个想完成的计划（例如：电影、音乐、动漫、设计、公益等），你可以在此发起项目向大家展示你的计划，并邀请喜欢你的计划的人以资金支持你。如果你愿意帮助别人，支持别人的梦想，你可以在众筹浏览到各行各业的人发起的项目计划，也可以成为发起人的梦想合伙人，当你们一起见证项目成功后，你还会获得发起人感谢你支持的回报。</span><br />\r\n</span></b>\r\n	</p>\r\n	<p class=\"p0\" style=\"margin-left:18.0000pt;\" align=\"left\">\r\n		<span style=\"font-size:14px;\" 宋体\";\"=\"\"><span><span style=\"font-size:14px;\"></span></span></span>\r\n	</p>\r\n<!--[if gte mso 9]><![endif]-->\r\n</div>','24','1415744764','1439757467','0','1','','0','0','0','1','','','','/ywlc/','','','1','1','','众筹网','众筹网');");

require("../../inc/footer.php");
?>